# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

xcodes(version: "14.1")

platform :ios do
  desc "The following lane runs the snapshot tests"
  lane :run_snapshots do
    run_tests(scheme: "LandmarksUITests", devices: "iPhone 8", output_directory: "fastlane/test_output/snapshots")
  end

  desc "The following lane records the snapshot tests"
  lane :record_snapshots do
    run_tests(scheme: "LandmarksUITests", devices: "iPhone 8", xcargs: "SNAPSHOT_RECORD_MODE='true'")
  end
end
