name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
          bundle install
          brew install robotsandpencils/made/xcodes


    - name: Run tests
      run: bundle exec fastlane run_snapshots

    # Artifacts allow you to persist data like test results after a job has completed, see https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts for how the artifacts works
    - name: Upload Fastlane Test results
      uses: actions/upload-artifact@v2
      with:
        name: Fastlane Test Results
        path: fastlane/test_output//snapshots

